-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.readers
(
    id integer NOT NULL,
    last_name character varying(32),
    first_name character varying(32) NOT NULL,
    patronymic character varying(32),
    street character varying(32) NOT NULL,
    city character varying(32) NOT NULL,
    zip_code character varying(6),
    phone character varying(10),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.books
(
    isbn_13 character varying(13) NOT NULL,
    title character varying(128) NOT NULL,
    publisher integer,
    year smallint,
    pages smallint,
    price money,
    quantity smallint NOT NULL,
    PRIMARY KEY (isbn_13)
);

CREATE TABLE IF NOT EXISTS public.authors
(
    id integer NOT NULL,
    last_name character varying(32) NOT NULL,
    first_name character varying(32),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.publishers
(
    id integer NOT NULL,
    name character varying(32) NOT NULL,
    city character varying(32),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.books_authors
(
    isbn_13 character varying(13) NOT NULL,
    author_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.loans
(
    reader_id integer NOT NULL,
    "isbn-13" character varying(13) NOT NULL,
    start_date date,
    due_date date,
    is_returned boolean
);

ALTER TABLE IF EXISTS public.books
    ADD CONSTRAINT publisher FOREIGN KEY (publisher)
    REFERENCES public.publishers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.books_authors
    ADD CONSTRAINT book FOREIGN KEY (isbn_13)
    REFERENCES public.books (isbn_13) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.books_authors
    ADD CONSTRAINT author FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.loans
    ADD CONSTRAINT book FOREIGN KEY ("isbn-13")
    REFERENCES public.books (isbn_13) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.loans
    ADD CONSTRAINT reader FOREIGN KEY (reader_id)
    REFERENCES public.readers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;