# version: "3.9"
# From Docker Compose documentation:
# "The top-level version property is defined 
# by the Compose Specification for backward compatibility."
#
name: homework-1-3
services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_DB: "junior_script"
      POSTGRES_USER: "peter"
      POSTGRES_PASSWORD: "peter"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pg_initdb:/docker-entrypoint-initdb.d:ro
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peter -d junior_script"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pg_data: