name: homework-2-att-1
services:
  db:
    image: postgres:latest
    container_name: pg-2-att-1
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - vol-2-att-1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  vol-2-att-1: